modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/DrMango14/Create-Design-n-Decor/issues"

[[mods]]
    modId="sweepsnap"
    version="${file.jarVersion}"
    displayName="SweepSnap"
    updateJSONURL="https://api.modrinth.com/updates/MOD/forge_updates.json"
    displayURL="https://modrinth.com/mod/MOD"
    logoFile="pack.png"
    authors="LopyLuna"
    description='''
INFO ABOUT MOD
'''

[[dependencies.sweepsnap]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sweepsnap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"