modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
#issueTrackerURL="NA"

[[mods]]
    modId="excavein"
    version="${file.jarVersion}"
    displayName="ExcaVein"
    updateJSONURL="https://api.modrinth.com/updates/excavein/forge_updates.json"
    displayURL="https://modrinth.com/mod/excavein"
    logoFile="pack.png"
    authors="LopyLuna"
    description='''
Excavein is a powerful & customizable vein mining / building tool. Players can select different modes to gather or place blocks efficiently, making gathering resources and building faster and more enjoyable.
'''

[[dependencies.excavein]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.excavein]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"