modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
#issueTrackerURL="NA"

[[mods]]
    modId="excavein"
    version="${file.jarVersion}"
    displayName="ExcaVein"
    updateJSONURL="https://api.modrinth.com/updates/MOD/forge_updates.json"
    displayURL="https://modrinth.com/mod/MOD"
    logoFile="pack.png"
    authors="LopyLuna"
    description='''
INFO ABOUT MOD
'''

[[dependencies.excavein]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.excavein]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"